language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm
jobs:
  include:
    - stage: test
      script: yarn test
      script: yarn eslint
    
    - stage: deploy
      script: yarn deploy
node_js:
    - '12'
git:
  depth: 3

script:
    - yarn build

notifications:
  email:
    recipients:
        - pokoyo.saz@gmail.com
        - auto.system365@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  targt-branch: gh-pages
  commit_message: "Deploy del Proyecto"
  on:
    branch: master